make: pflichtenheft.tex pflichtenheft.gls
	pdflatex pflichtenheft.tex

pflichtenheft.gls: pflichtenheft.glo
	makeglossaries pflichtenheft.glo

pflichtenheft.glo: pflichtenheft.tex
	pdflatex pflichtenheft.tex
